### PR TITLE
Removed old changelog script

### PR DESCRIPTION
**Pull request by scottanthonymurray**
Replaced by GitHub Action.

See https://app.asana.com/0/1199946964816580/1201119412550088/f

### CODE REVIEW

**Comment by levimcg** [comment]
@scottanthonymurray Can you also remove the two dependencies that the old changelog script used so that they are no longer in package.json?

```npm uninstall -D axios readline```

**Comment by levimcg** [comment]
@scottanthonymurray Updated that comment above. It's just the one dep. that needs uninstalled `npm uninstall -D axios`

**Comment by scottanthonymurray** [comment]
@levimcg Thanks for catching that! I've uninstalled `axios`.

**Review by levimcg — APPROVED** [review]
Nice, looks great!

**Pull request merged**
