### PR TITLE
Refactored radio input in fractal

### PR DESCRIPTION
**Pull request by illusivesunrae**
In this PR:

- Refactored code to allow replacement options within other examples using an array (options)

### CODE REVIEW

**Comment by levimcg** [comment]
@illusivesunrae Would it make sense to go ahead and convert this to Nunjucks once @zttodd merges the branch that switched the template engine?

**Comment by illusivesunrae** [comment]
Probably, lol. 🙃

**Comment by levimcg** [comment]
Cool, yeah, I guess it doesn't make much sense to merge it and then do it over again. Sorry!

Once you've had a chance to refactor it to a nunjucks template, I can take a look asap.

**Comment by illusivesunrae** [comment]
@levimcg Alright, this should be ready for review now. 🙂

**Pull request merged**
