### PR TITLE
Updated Sass to use math.div()

### PR DESCRIPTION
**Pull request by scottanthonymurray**
The `/` operator for division is deprecated.

See https://app.asana.com/0/1199946964816580/1200802859946356/f

### CODE REVIEW

**Comment by scottanthonymurray** [comment]
@levimcg Some division expressions had enclosing parentheses around them presumably for syntax or order-of-operations reasons. I left them as they were, but I think the use of `math.div()` makes a lot of them redundant so let me know if you'd like me to remove them as well.

**Review by levimcg — CHANGES_REQUESTED** [review]
@scottanthonymurray We'll actually have to update to at least `sass@1.33.0` before we can make this update. Right now the sass task errors out because the `.div` function is not available in the version (`1.25.0`). Here's the docs on that: https://sass-lang.com/documentation/modules/math#other-functions

That's my bad. I had written up [a separate task](https://app.asana.com/0/1199946964816580/1201366217856409/f) for updating to the latest sass and should have mentioned that in this task.

**Review by levimcg — COMMENTED** [review]
@scottanthonymurray Great, thanks for updating that dependency.

RE: the extra parenthesis, if you could go ahead and removed those, that would be awesome. You're right, with the new math.div function it makes them unnecessary. They were mostly there for readability reasons.

**Review by levimcg — APPROVED** [review]
Nice, thank you!

**Pull request merged**
